# Generated by Django 6.0.4 on 2026-06-25 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_project_assigned_by_project_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Paid', 'Paid Leave'), ('Unpaid', 'Unpaid Leave')], default='Paid', max_length=20),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='HRA')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PF')),
                ('esi_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ESI')),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TDS')),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('working_days', models.PositiveSmallIntegerField(default=26)),
                ('days_present', models.PositiveSmallIntegerField(default=26)),
                ('days_absent', models.PositiveSmallIntegerField(default=0)),
                ('leaves_taken', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Processing', 'Processing')], default='Pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('payslip_pdf', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('employee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('uan', models.CharField(blank=True, max_length=20, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('unpaid_leave_days', models.PositiveSmallIntegerField(default=0)),
                ('half_days', models.PositiveSmallIntegerField(default=0)),
                ('holidays', models.PositiveSmallIntegerField(default=0)),
                ('week_offs', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(limit_choices_to={'role__in': ['Employee', 'TeamLead', 'Manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GENERATE', 'Payroll Generated'), ('REGENERATE', 'Payroll Regenerated'), ('LOCK', 'Payslip Locked'), ('UNLOCK', 'Payslip Unlocked'), ('PAID', 'Salary Marked as Paid'), ('EMAIL', 'Payslip Emailed'), ('DOWNLOAD', 'Payslip Downloaded')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hr.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='hr.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_enabled', models.BooleanField(default=True)),
                ('pf_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('pf_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('esi_enabled', models.BooleanField(default=True)),
                ('esi_rate', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('esi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pt_enabled', models.BooleanField(default=True)),
                ('pt_amount', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('uan', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
