# Generated by Django 6.0.4 on 2026-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
