# Generated by Django 6.0.4 on 2026-06-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_add_remarks_to_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandwich_leave_enabled', models.BooleanField(default=False, help_text='When ON, Weekly Offs and Holidays sandwiched between two consecutive Absent / Unpaid-Leave days are automatically converted to Absent (Loss of Pay).', verbose_name='Enable Sandwich Leave Policy')),
            ],
            options={
                'verbose_name': 'HR Settings',
                'verbose_name_plural': 'HR Settings',
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='sandwich_leave_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sandwich Leave Days'),
        ),
    ]
