# Generated by Django 6.0.4 on 2026-06-29 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_payslip_approved_at_payslip_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_check_in', models.DateTimeField(blank=True, null=True)),
                ('original_check_out', models.DateTimeField(blank=True, null=True)),
                ('original_status', models.CharField(blank=True, max_length=50)),
                ('original_total_hours', models.FloatField(blank=True, null=True)),
                ('original_remarks', models.TextField(blank=True, default='')),
                ('new_check_in', models.DateTimeField(blank=True, null=True)),
                ('new_check_out', models.DateTimeField(blank=True, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('new_total_hours', models.FloatField(blank=True, null=True)),
                ('new_remarks', models.TextField(blank=True, default='')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('md_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corrections', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='hr.attendance')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_corrections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
